"""Random Rule Forest.

An interpretable ensemble framework for binary classification based on YES/NO questions
generated by LLMs.
"""

from ._rrf import RRF, QuestionExclusion
from ._types import EmbeddingModel, AnsSimilarityFunc

__all__ = ["RRF", "QuestionExclusion", "EmbeddingModel", "AnsSimilarityFunc"]
