name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --with dev,docs

      - name: Lint (ruff)
        run: |
          poetry run ruff check .

      - name: Type check (pyright)
        run: |
          poetry run pyright

      - name: Tests (pytest)
        run: |
          poetry run pytest -q

      - name: Build docs
        continue-on-error: true
        run: |
          poetry run sphinx-build -b html docs/source docs/_build

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
